#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DisplayPort-1 --pos 0x0 --primary \
       --output HDMI-A-0 --pos 1920x0 \
       --output DisplayPort-0 --pos 3840x0

bspc monitor DisplayPort-1 -d Passwords Teams A B C D
bspc monitor HDMI-A-0 -d Internet Email 1 2 3 Steam
bspc monitor DisplayPort-0 -d I II III IV V VI VII VIII IX X Game

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Brave-browser desktop=Internet
bspc rule -a org.mozilla.Thunderbird desktop=Email
bspc rule -a steam desktop=Steam follow=no
bspc rule -a steamwebhelper desktop=Steam follow=no
bspc rule -a KeePassXC desktop=Passwords
bspc rule -a teams-for-linux desktop=Teams
bspc rule -a firefox desktop=A

picom --config $HOME/.config/picom/picom.conf &
dunst &
polybar middle &
polybar right &
polybar left &

$HOME/.dotfiles/scripts/bspwm/feh-wallpaper.sh &

systemctl --user import-environment PATH DBUS_SESSION_BUS_ADDRESS
systemctl --user import-environment DISPLAY XAUTHORITY
systemctl --no-block --user start xsession.target
systemctl --no-block --user start feh-wallpaper.timer
